# Generated by Django 5.0.2 on 2024-02-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_location_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
